export const SET_STORIES = 'SET_STORIES';

export const FETCH_STORIES_START = 'FETCH_STORIES_START';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAIL = 'FETCH_STORIES_FAIL';

export const FETCH_STORIES_ID_START = 'FETCH_STORIES_ID_START';
export const FETCH_STORIES_ID_SUCCESS = 'FETCH_STORIES_ID_SUCCESS';
export const FETCH_STORIES_ID_FAIL = 'FETCH_STORIES_ID_FAIL';